/* **********************************************************************************************
  WARNING: DO NOT EDIT this file except from inside the react-starter-template repository. Changes made to this file inside child repos will NOT be reflected in the parent source template repository, and will generate code conflicts.
*********************************************************************************************** */
import React from 'react';
import moment from 'moment';
import PropTypes from 'prop-types';
import config from 'app/config';
import 'template/styles/components/Error.css';

const Error = ({ message, absolutePosition }) => (
  <div className={`row${absolutePosition ? ' error-pos-absolute' : ''}`}>
    <div className="col-sm-12">
      <div className="alert alert-danger alert-sm">
        <p>
          There was an error.&nbsp;
          {config.hasFeedbackForm
            && (
              <span>
                You may report issues using&nbsp;
                <a
                  href={config.feedbackURL}
                  target="_blank"
                  rel="noopener noreferrer"
                  style={{ color: '#fff', textDecoration: 'underline' }}
                >
                  this form
                </a>
                .
              </span>
            )
          }
          {!config.hasFeedbackForm && (
            <span>Please report issues to help@ashevillenc.gov.</span>
          )}
        </p>
        <p>
          Time:&nbsp;
          {moment().format('M/DD/YYYY HH:mm:ss Z')}
          &nbsp;UTC
        </p>
        <p>
          <span>Error details:&nbsp;</span>
          {message}
        </p>
      </div>
    </div>
  </div>
);

Error.propTypes = {
  message: PropTypes.string,
  absolutePosition: PropTypes.bool,
};

Error.defaultProps = {
  message: 'Error message',
  absolutePosition: false,
};

export default Error;
