/* **********************************************************************************************
  WARNING: DO NOT EDIT this file except from inside the react-starter-template repository. Changes made to this file inside child repos will NOT be reflected in the parent source template repository, and will generate code conflicts.
*********************************************************************************************** */
import React from 'react';
import moment from 'moment';
import config from 'app/config';

class ErrorBoundary extends React.Component {
  constructor() {
    super();
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(error) {
    // Update state so the next render will show the fallback UI.
    return { hasError: true };
  }

  render() {
    if (this.state.hasError) {
      // You can render any custom fallback UI
      return (<div className="alert alert-danger alert-sm">
        <p>
          There was an error.&nbsp;
          {config.hasFeedbackForm
            && (
              <span>
                You may report issues using&nbsp;
                <a
                  href={config.feedbackURL}
                  target="_blank"
                  rel="noopener noreferrer"
                  style={{ color: '#fff', textDecoration: 'underline' }}
                >
                  this form
                </a>
                .
              </span>
            )
          }
          {!config.hasFeedbackForm && (
            <span>Please report issues to help@ashevillenc.gov.</span>
          )}
        </p>
        <p>
          Time:&nbsp;
          {moment().format('M/DD/YYYY HH:mm:ss Z')}
          &nbsp;UTC
        </p>
      </div>)
    }
    return this.props.children;
  }
}

export default Error;
