/* **********************************************************************************************
  WARNING: DO NOT EDIT this file except from inside the react-starter-template repository. Changes made to this file inside child repos will NOT be reflected in the parent source template repository, and will generate code conflicts.
*********************************************************************************************** */
import React from 'react';
import moment from 'moment';
import config from 'app/config';


const FourOhFour = () => (
  <div className="alert alert-danger alert-sm">
    <p>
      {`The URL ${window.location.href} could not be found.  Maybe there is a typo?`}
    </p>
    <p>
      If you think you&apos;re seeing this message in error, let us know.&nbsp;
      {config.hasFeedbackForm && config.useFeedbackForErrors
        && (
          <span>
            You may report issues using&nbsp;
            <a
              href={config.feedbackURL}
              target="_blank"
              rel="noopener noreferrer"
              style={{ color: '#fff', textDecoration: 'underline' }}
            >
              this form
            </a>
            .
          </span>
        )
      }
      {(!config.hasFeedbackForm || !config.useFeedbackForErrors) && (
        <span>Please report issues to help@ashevillenc.gov.</span>
      )}
    </p>
    <p>
      Time:&nbsp;
      {moment().format('M/DD/YYYY HH:mm:ss Z')}
      &nbsp;UTC
    </p>
  </div>
);


export default FourOhFour;
